function solver_setup(platform)
%% Setup script for solver

gsl_path = '/usr/local/include/gsl';
gsl_lib = '/usr/local/lib';

cuda_bin = '/usr/local/cuda/bin';
cuda_lib = '/usr/local/cuda/lib';

if nargin == 0 || ~strcmp(platform, 'gpu')
  unix(sprintf('make solver.o -f Makefile -C .. IFLAGS=-D__MEX__'));
  mex('-largeArrayDims', ...
      '-I..', ['-I' gsl_path], ...
      '-lgsl', '-lm', ['-L' gsl_lib],...
      '../solver.o', 'solver_matlab.cpp');
else
  unix(sprintf(['export PATH=$PATH:%s;' ...
                'export DYLD_LIBRARY_PATH=%s:$DYLD_LIBRARY_PATH;' ...
                'make solver_cu.o -f Makefile -C .. IFLAGS=-D__MEX__;' ...
                'make solver_cu_link.o -f Makefile -C .. IFLAGS=-D__MEX__'], ...
               cuda_bin, cuda_lib));
  mex('-v','-largeArrayDims',...
      '-I..',...
      ['-L' cuda_lib], '-lcudart', '-lcublas', ...
      'solver_matlab.cpp', '../solver_cu.o', '../solver_cu_link.o')
end


